import "./globals.css";
import '@coreui/coreui/dist/css/coreui.min.css';
import Header from "@/components/Header";
import Footer from "@/components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <div className="w-full">
          <Header/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
